### ISSUE TITLE
Qi Charger Stops Charging

### ISSUE THREAD

**Issue by eighthrazz** [mudar/SnooZy#15]
I have a Samsung Qi charger that stops charging when my phone reaches 100%. The problem with that is by the time I wake up in the morning it's already down to %93. Can your app continually keep my phone at 100% charged while on the wireless charger?

**Comment by mudar** [comment]
Thanks for the feedback, but sorry to say there isn't much I can do about this specific issue. It's probably related to your phone settings or to a functionnality of the charger.

Most users complain about the opposite: charging reaches 100%, stop charging, battery goes down to 99%, charging resumes (and screen light goes on), back to 100% and the story repeats..

This is the issue addressed by SnooZy (the annoying light). There might be a different app that handles that, or maybe a different charger.

Sorry for not having a better answer!

**Comment by eighthrazz** [comment]
Thanks for the quick response!
